### ISSUE TITLE
Cannot convert from 'DbContextGeneratorWithCodeFirst.QAContext' to 'string'

### ISSUE THREAD

**Issue by aradhaghi** [coni2k/DbContextGeneratorWithCodeFirst#1]
I pull down the sample and cannot get it working. 

I'm getting following error:
cannot convert from 'DbContextGeneratorWithCodeFirst.QAContext' to 'string'.

Any idea what can cause this issue?

**Comment by coni2k** [comment]
@aradhaghi Can you try it again with the updated version? 

I just updated the project to work with Visual Studio 2017 and Entity Framework 6.2.0, and currently it works on my machine.

Let me know if you still have any issues.

**Comment by aradhaghi** [comment]
It's working fine with VS 2017 now. Thank you.
